// This software is released into the Public Domain.  See copying.txt for details.
package org.villseriol.osmosis.transliterate.v0_6.unicode.mapping.characterset;

import java.util.ArrayList;
import java.util.List;

import org.villseriol.osmosis.transliterate.v0_6.unicode.Icu4jUtils;
import org.villseriol.osmosis.transliterate.v0_6.unicode.UnicodeRange;
import org.villseriol.osmosis.transliterate.v0_6.unicode.UnicodeRanges;
import org.villseriol.osmosis.transliterate.v0_6.unicode.Unimap;

import com.ibm.icu.text.ReplaceableString;
import com.ibm.icu.text.Transliterator;


@UnicodeRanges(UnicodeRange.CJK_COMPATIBILITY)
public class CjkCompatibilityMapper implements Unimap {
    private static final Transliterator TRANSLITERATOR;

    static {
        List<String> rules = new ArrayList<>();

        rules.add("㌀ > 'アパート';");
        rules.add("㌁ > 'アルファ';");
        rules.add("㌂ > 'アンペア';");
        rules.add("㌃ > 'アール';");
        rules.add("㌄ > 'イニング';");
        rules.add("㌅ > 'インチ';");
        rules.add("㌆ > 'ウォン';");
        rules.add("㌇ > 'エスクード';");
        rules.add("㌈ > 'エーカー';");
        rules.add("㌉ > 'オンス';");
        rules.add("㌊ > 'オーム';");
        rules.add("㌋ > 'カイリ';");
        rules.add("㌌ > 'カラット';");
        rules.add("㌍ > 'カロリー';");
        rules.add("㌎ > 'ガロン';");
        rules.add("㌏ > 'ガンマ';");
        rules.add("㌐ > 'ギガ';");
        rules.add("㌑ > 'ギニー';");
        rules.add("㌒ > 'キュリー';");
        rules.add("㌓ > 'ギルダー';");
        rules.add("㌔ > 'キロ';");
        rules.add("㌕ > 'キログラム';");
        rules.add("㌖ > 'キロメートル';");
        rules.add("㌗ > 'キロワット';");
        rules.add("㌘ > 'グラム';");
        rules.add("㌙ > 'グラムトン';");
        rules.add("㌚ > 'クルゼイロ';");
        rules.add("㌛ > 'クローネ';");
        rules.add("㌜ > 'ケース';");
        rules.add("㌝ > 'コルナ';");
        rules.add("㌞ > 'コーポ';");
        rules.add("㌟ > 'サイクル';");
        rules.add("㌠ > 'サンチーム';");
        rules.add("㌡ > 'シリング';");
        rules.add("㌢ > 'センチ';");
        rules.add("㌣ > 'セント';");
        rules.add("㌤ > 'ダース';");
        rules.add("㌥ > 'デシ';");
        rules.add("㌦ > 'ドル';");
        rules.add("㌧ > 'トン';");
        rules.add("㌨ > 'ナノ';");
        rules.add("㌩ > 'ノット';");
        rules.add("㌪ > 'ハイツ';");
        rules.add("㌫ > 'パーセント';");
        rules.add("㌬ > ' ';");
        rules.add("㌭ > 'バーレル';");
        rules.add("㌮ > 'ピアストル';");
        rules.add("㌯ > 'ピクル';");
        rules.add("㌰ > 'ピコ';");
        rules.add("㌱ > 'ビル';");
        rules.add("㌲ > 'ファラッド';");
        rules.add("㌳ > 'フィート';");
        rules.add("㌴ > 'ブッシェル';");
        rules.add("㌵ > 'フラン';");
        rules.add("㌶ > 'ヘクタール';");
        rules.add("㌷ > 'ペソ';");
        rules.add("㌸ > 'ペニヒ';");
        rules.add("㌹ > 'ヘルツ';");
        rules.add("㌺ > 'ペンス';");
        rules.add("㌻ > 'ページ';");
        rules.add("㌼ > 'ベータ';");
        rules.add("㌽ > 'ポイント';");
        rules.add("㌾ > 'ボルト';");
        rules.add("㌿ > 'ホン';");
        rules.add("㍀ > 'ポンド';");
        rules.add("㍁ > 'ホール';");
        rules.add("㍂ > 'ホーン';");
        rules.add("㍃ > 'マイクロ';");
        rules.add("㍄ > 'マイル';");
        rules.add("㍅ > 'マッハ';");
        rules.add("㍆ > 'マルク';");
        rules.add("㍇ > 'マンション';");
        rules.add("㍈ > 'ミクロン';");
        rules.add("㍉ > 'ミリ';");
        rules.add("㍊ > 'ミリバール';");
        rules.add("㍋ > 'メガ';");
        rules.add("㍌ > 'メガトン';");
        rules.add("㍍ > 'メートル';");
        rules.add("㍎ > 'ヤード';");
        rules.add("㍏ > 'ヤール';");
        rules.add("㍐ > 'ユアン';");
        rules.add("㍑ > 'リットル';");
        rules.add("㍒ > 'リラ';");
        rules.add("㍓ > 'ルピー';");
        rules.add("㍔ > 'ルーブル';");
        rules.add("㍕ > 'レム';");
        rules.add("㍖ > 'レントゲン';");
        rules.add("㍗ > 'ワット';");
        rules.add("㍘ > '0点';");
        rules.add("㍙ > '1点';");
        rules.add("㍚ > '2点';");
        rules.add("㍛ > '3点';");
        rules.add("㍜ > '4点';");
        rules.add("㍝ > '5点';");
        rules.add("㍞ > '6点';");
        rules.add("㍟ > '7点';");
        rules.add("㍠ > '8点';");
        rules.add("㍡ > '9点';");
        rules.add("㍢ > '10点';");
        rules.add("㍣ > '11点';");
        rules.add("㍤ > '12点';");
        rules.add("㍥ > '13点';");
        rules.add("㍦ > '14点';");
        rules.add("㍧ > '15点';");
        rules.add("㍨ > '16点';");
        rules.add("㍩ > '17点';");
        rules.add("㍪ > '18点';");
        rules.add("㍫ > '19点';");
        rules.add("㍬ > '20点';");
        rules.add("㍭ > '21点';");
        rules.add("㍮ > '22点';");
        rules.add("㍯ > '23点';");
        rules.add("㍰ > '24点';");
        rules.add("㍱ > 'hPa';");
        rules.add("㍲ > 'da';");
        rules.add("㍳ > 'AU';");
        rules.add("㍴ > 'bar';");
        rules.add("㍵ > 'oV';");
        rules.add("㍶ > 'pc';");
        rules.add("㍷ > 'dm';");
        rules.add("㍸ > 'dm2';");
        rules.add("㍹ > 'dm3';");
        rules.add("㍺ > 'IU';");
        rules.add("㍻ > '平成';");
        rules.add("㍼ > '昭和';");
        rules.add("㍽ > '大正';");
        rules.add("㍾ > '明治';");
        rules.add("㍿ > '株式会社';");
        rules.add("㎀ > 'pA';");
        rules.add("㎁ > 'nA';");
        rules.add("㎂ > 'uA';");
        rules.add("㎃ > 'mA';");
        rules.add("㎄ > 'kA';");
        rules.add("㎅ > 'KB';");
        rules.add("㎆ > 'MB';");
        rules.add("㎇ > 'GB';");
        rules.add("㎈ > 'cal';");
        rules.add("㎉ > 'kcal';");
        rules.add("㎊ > 'pF';");
        rules.add("㎋ > 'nF';");
        rules.add("㎌ > 'uF';");
        rules.add("㎍ > 'ug';");
        rules.add("㎎ > 'mg';");
        rules.add("㎏ > 'kg';");
        rules.add("㎐ > 'Hz';");
        rules.add("㎑ > 'kHz';");
        rules.add("㎒ > 'MHz';");
        rules.add("㎓ > 'GHz';");
        rules.add("㎔ > 'THz';");
        rules.add("㎕ > 'ul';");
        rules.add("㎖ > 'ml';");
        rules.add("㎗ > 'dl';");
        rules.add("㎘ > 'kl';");
        rules.add("㎙ > 'fm';");
        rules.add("㎚ > 'nm';");
        rules.add("㎛ > 'um';");
        rules.add("㎜ > 'mm';");
        rules.add("㎝ > 'cm';");
        rules.add("㎞ > 'km';");
        rules.add("㎟ > 'mm2';");
        rules.add("㎠ > 'cm2';");
        rules.add("㎡ > 'm2';");
        rules.add("㎢ > 'km2';");
        rules.add("㎣ > 'mm3';");
        rules.add("㎤ > 'cm3';");
        rules.add("㎥ > 'm3';");
        rules.add("㎦ > 'km3';");
        rules.add("㎧ > 'm/s';");
        rules.add("㎨ > 'm/s2';");
        rules.add("㎩ > 'Pa';");
        rules.add("㎪ > 'kPa';");
        rules.add("㎫ > 'MPa';");
        rules.add("㎬ > 'GPa';");
        rules.add("㎭ > 'rad';");
        rules.add("㎮ > 'rad/s';");
        rules.add("㎯ > 'rad/s2';");
        rules.add("㎰ > 'ps';");
        rules.add("㎱ > 'ns';");
        rules.add("㎲ > 'us';");
        rules.add("㎳ > 'ms';");
        rules.add("㎴ > 'pV';");
        rules.add("㎵ > 'nV';");
        rules.add("㎶ > 'uV';");
        rules.add("㎷ > 'mV';");
        rules.add("㎸ > 'kV';");
        rules.add("㎹ > 'MV';");
        rules.add("㎺ > 'pW';");
        rules.add("㎻ > 'nW';");
        rules.add("㎼ > 'uW';");
        rules.add("㎽ > 'mW';");
        rules.add("㎾ > 'kW';");
        rules.add("㎿ > 'MW';");
        rules.add("㏀ > 'kohm';");
        rules.add("㏁ > 'Mohm';");
        rules.add("㏂ > 'a.m.';");
        rules.add("㏃ > 'Bq';");
        rules.add("㏄ > 'cc';");
        rules.add("㏅ > 'cd';");
        rules.add("㏆ > 'C/kg';");
        rules.add("㏇ > 'Co.';");
        rules.add("㏈ > 'dB';");
        rules.add("㏉ > 'Gy';");
        rules.add("㏊ > 'ha';");
        rules.add("㏋ > 'HP';");
        rules.add("㏌ > 'in';");
        rules.add("㏍ > 'KK';");
        rules.add("㏎ > 'KM';");
        rules.add("㏏ > 'kt';");
        rules.add("㏐ > 'lm';");
        rules.add("㏑ > 'ln';");
        rules.add("㏒ > 'log';");
        rules.add("㏓ > 'lx';");
        rules.add("㏔ > 'mb';");
        rules.add("㏕ > 'mil';");
        rules.add("㏖ > 'mol';");
        rules.add("㏗ > 'PH';");
        rules.add("㏘ > 'p.m.';");
        rules.add("㏙ > 'PPM';");
        rules.add("㏚ > 'PR';");
        rules.add("㏛ > 'sr';");
        rules.add("㏜ > 'Sv';");
        rules.add("㏝ > 'Wb';");
        rules.add("㏞ > 'V/m';");
        rules.add("㏟ > 'A/m';");
        rules.add("㏠ > '1日';");
        rules.add("㏡ > '2日';");
        rules.add("㏢ > '3日';");
        rules.add("㏣ > '4日';");
        rules.add("㏤ > '5日';");
        rules.add("㏥ > '6日';");
        rules.add("㏦ > '7日';");
        rules.add("㏧ > '8日';");
        rules.add("㏨ > '9日';");
        rules.add("㏩ > '10日';");
        rules.add("㏪ > '11日';");
        rules.add("㏫ > '12日';");
        rules.add("㏬ > '13日';");
        rules.add("㏭ > '14日';");
        rules.add("㏮ > '15日';");
        rules.add("㏯ > '16日';");
        rules.add("㏰ > '17日';");
        rules.add("㏱ > '18日';");
        rules.add("㏲ > '19日';");
        rules.add("㏳ > '20日';");
        rules.add("㏴ > '21日';");
        rules.add("㏵ > '22日';");
        rules.add("㏶ > '23日';");
        rules.add("㏷ > '24日';");
        rules.add("㏸ > '25日';");
        rules.add("㏹ > '26日';");
        rules.add("㏺ > '27日';");
        rules.add("㏻ > '28日';");
        rules.add("㏼ > '29日';");
        rules.add("㏽ > '30日';");
        rules.add("㏾ > '31日';");
        rules.add("㏿ > 'gal';");

        String rule = Icu4jUtils.createIcu4jRule(CjkCompatibilityMapper.class, rules);

        TRANSLITERATOR = Transliterator.createFromRules("CjkCompatibility-Normalized", rule, Transliterator.FORWARD);
    }

    @Override
    public String action(String input) {
        return TRANSLITERATOR.transliterate(input);
    }


    @Override
    public void action(StringBuffer input) {
        TRANSLITERATOR.transliterate(new ReplaceableString(input));
    }
}
