// This software is released into the Public Domain.  See copying.txt for details.
package org.villseriol.osmosis.transliterate.v0_6.unicode.mapping.characterset;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

public class CjkUnifiedIdeographsExtensionDMapperTest extends KakasiMapperTest {
    @Test
    public void testMapsToSomething() {
        assertEquals("?", transform.action("𫝀")); // 2B740 CJK UNIFIED IDEOGRAPH-2B740
        assertEquals("?", transform.action("𫝁")); // 2B741 CJK UNIFIED IDEOGRAPH-2B741
        assertEquals("?", transform.action("𫝂")); // 2B742 CJK UNIFIED IDEOGRAPH-2B742
        assertEquals("?", transform.action("𫝃")); // 2B743 CJK UNIFIED IDEOGRAPH-2B743
        assertEquals("?", transform.action("𫝄")); // 2B744 CJK UNIFIED IDEOGRAPH-2B744
        assertEquals("?", transform.action("𫝅")); // 2B745 CJK UNIFIED IDEOGRAPH-2B745
        assertEquals("?", transform.action("𫝆")); // 2B746 CJK UNIFIED IDEOGRAPH-2B746
        assertEquals("?", transform.action("𫝇")); // 2B747 CJK UNIFIED IDEOGRAPH-2B747
        assertEquals("?", transform.action("𫝈")); // 2B748 CJK UNIFIED IDEOGRAPH-2B748
        assertEquals("?", transform.action("𫝉")); // 2B749 CJK UNIFIED IDEOGRAPH-2B749
        assertEquals("?", transform.action("𫝊")); // 2B74A CJK UNIFIED IDEOGRAPH-2B74A
        assertEquals("?", transform.action("𫝋")); // 2B74B CJK UNIFIED IDEOGRAPH-2B74B
        assertEquals("?", transform.action("𫝌")); // 2B74C CJK UNIFIED IDEOGRAPH-2B74C
        assertEquals("?", transform.action("𫝍")); // 2B74D CJK UNIFIED IDEOGRAPH-2B74D
        assertEquals("?", transform.action("𫝎")); // 2B74E CJK UNIFIED IDEOGRAPH-2B74E
        assertEquals("?", transform.action("𫝏")); // 2B74F CJK UNIFIED IDEOGRAPH-2B74F
        assertEquals("?", transform.action("𫝐")); // 2B750 CJK UNIFIED IDEOGRAPH-2B750
        assertEquals("?", transform.action("𫝑")); // 2B751 CJK UNIFIED IDEOGRAPH-2B751
        assertEquals("?", transform.action("𫝒")); // 2B752 CJK UNIFIED IDEOGRAPH-2B752
        assertEquals("?", transform.action("𫝓")); // 2B753 CJK UNIFIED IDEOGRAPH-2B753
        assertEquals("?", transform.action("𫝔")); // 2B754 CJK UNIFIED IDEOGRAPH-2B754
        assertEquals("?", transform.action("𫝕")); // 2B755 CJK UNIFIED IDEOGRAPH-2B755
        assertEquals("?", transform.action("𫝖")); // 2B756 CJK UNIFIED IDEOGRAPH-2B756
        assertEquals("?", transform.action("𫝗")); // 2B757 CJK UNIFIED IDEOGRAPH-2B757
        assertEquals("?", transform.action("𫝘")); // 2B758 CJK UNIFIED IDEOGRAPH-2B758
        assertEquals("?", transform.action("𫝙")); // 2B759 CJK UNIFIED IDEOGRAPH-2B759
        assertEquals("?", transform.action("𫝚")); // 2B75A CJK UNIFIED IDEOGRAPH-2B75A
        assertEquals("?", transform.action("𫝛")); // 2B75B CJK UNIFIED IDEOGRAPH-2B75B
        assertEquals("?", transform.action("𫝜")); // 2B75C CJK UNIFIED IDEOGRAPH-2B75C
        assertEquals("?", transform.action("𫝝")); // 2B75D CJK UNIFIED IDEOGRAPH-2B75D
        assertEquals("?", transform.action("𫝞")); // 2B75E CJK UNIFIED IDEOGRAPH-2B75E
        assertEquals("?", transform.action("𫝟")); // 2B75F CJK UNIFIED IDEOGRAPH-2B75F
        assertEquals("?", transform.action("𫝠")); // 2B760 CJK UNIFIED IDEOGRAPH-2B760
        assertEquals("?", transform.action("𫝡")); // 2B761 CJK UNIFIED IDEOGRAPH-2B761
        assertEquals("?", transform.action("𫝢")); // 2B762 CJK UNIFIED IDEOGRAPH-2B762
        assertEquals("?", transform.action("𫝣")); // 2B763 CJK UNIFIED IDEOGRAPH-2B763
        assertEquals("?", transform.action("𫝤")); // 2B764 CJK UNIFIED IDEOGRAPH-2B764
        assertEquals("?", transform.action("𫝥")); // 2B765 CJK UNIFIED IDEOGRAPH-2B765
        assertEquals("?", transform.action("𫝦")); // 2B766 CJK UNIFIED IDEOGRAPH-2B766
        assertEquals("?", transform.action("𫝧")); // 2B767 CJK UNIFIED IDEOGRAPH-2B767
        assertEquals("?", transform.action("𫝨")); // 2B768 CJK UNIFIED IDEOGRAPH-2B768
        assertEquals("?", transform.action("𫝩")); // 2B769 CJK UNIFIED IDEOGRAPH-2B769
        assertEquals("?", transform.action("𫝪")); // 2B76A CJK UNIFIED IDEOGRAPH-2B76A
        assertEquals("?", transform.action("𫝫")); // 2B76B CJK UNIFIED IDEOGRAPH-2B76B
        assertEquals("?", transform.action("𫝬")); // 2B76C CJK UNIFIED IDEOGRAPH-2B76C
        assertEquals("?", transform.action("𫝭")); // 2B76D CJK UNIFIED IDEOGRAPH-2B76D
        assertEquals("?", transform.action("𫝮")); // 2B76E CJK UNIFIED IDEOGRAPH-2B76E
        assertEquals("?", transform.action("𫝯")); // 2B76F CJK UNIFIED IDEOGRAPH-2B76F
        assertEquals("?", transform.action("𫝰")); // 2B770 CJK UNIFIED IDEOGRAPH-2B770
        assertEquals("?", transform.action("𫝱")); // 2B771 CJK UNIFIED IDEOGRAPH-2B771
        assertEquals("?", transform.action("𫝲")); // 2B772 CJK UNIFIED IDEOGRAPH-2B772
        assertEquals("?", transform.action("𫝳")); // 2B773 CJK UNIFIED IDEOGRAPH-2B773
        assertEquals("?", transform.action("𫝴")); // 2B774 CJK UNIFIED IDEOGRAPH-2B774
        assertEquals("?", transform.action("𫝵")); // 2B775 CJK UNIFIED IDEOGRAPH-2B775
        assertEquals("?", transform.action("𫝶")); // 2B776 CJK UNIFIED IDEOGRAPH-2B776
        assertEquals("?", transform.action("𫝷")); // 2B777 CJK UNIFIED IDEOGRAPH-2B777
        assertEquals("?", transform.action("𫝸")); // 2B778 CJK UNIFIED IDEOGRAPH-2B778
        assertEquals("?", transform.action("𫝹")); // 2B779 CJK UNIFIED IDEOGRAPH-2B779
        assertEquals("?", transform.action("𫝺")); // 2B77A CJK UNIFIED IDEOGRAPH-2B77A
        assertEquals("?", transform.action("𫝻")); // 2B77B CJK UNIFIED IDEOGRAPH-2B77B
        assertEquals("?", transform.action("𫝼")); // 2B77C CJK UNIFIED IDEOGRAPH-2B77C
        assertEquals("?", transform.action("𫝽")); // 2B77D CJK UNIFIED IDEOGRAPH-2B77D
        assertEquals("?", transform.action("𫝾")); // 2B77E CJK UNIFIED IDEOGRAPH-2B77E
        assertEquals("?", transform.action("𫝿")); // 2B77F CJK UNIFIED IDEOGRAPH-2B77F
        assertEquals("?", transform.action("𫞀")); // 2B780 CJK UNIFIED IDEOGRAPH-2B780
        assertEquals("?", transform.action("𫞁")); // 2B781 CJK UNIFIED IDEOGRAPH-2B781
        assertEquals("?", transform.action("𫞂")); // 2B782 CJK UNIFIED IDEOGRAPH-2B782
        assertEquals("?", transform.action("𫞃")); // 2B783 CJK UNIFIED IDEOGRAPH-2B783
        assertEquals("?", transform.action("𫞄")); // 2B784 CJK UNIFIED IDEOGRAPH-2B784
        assertEquals("?", transform.action("𫞅")); // 2B785 CJK UNIFIED IDEOGRAPH-2B785
        assertEquals("?", transform.action("𫞆")); // 2B786 CJK UNIFIED IDEOGRAPH-2B786
        assertEquals("?", transform.action("𫞇")); // 2B787 CJK UNIFIED IDEOGRAPH-2B787
        assertEquals("?", transform.action("𫞈")); // 2B788 CJK UNIFIED IDEOGRAPH-2B788
        assertEquals("?", transform.action("𫞉")); // 2B789 CJK UNIFIED IDEOGRAPH-2B789
        assertEquals("?", transform.action("𫞊")); // 2B78A CJK UNIFIED IDEOGRAPH-2B78A
        assertEquals("?", transform.action("𫞋")); // 2B78B CJK UNIFIED IDEOGRAPH-2B78B
        assertEquals("?", transform.action("𫞌")); // 2B78C CJK UNIFIED IDEOGRAPH-2B78C
        assertEquals("?", transform.action("𫞍")); // 2B78D CJK UNIFIED IDEOGRAPH-2B78D
        assertEquals("?", transform.action("𫞎")); // 2B78E CJK UNIFIED IDEOGRAPH-2B78E
        assertEquals("?", transform.action("𫞏")); // 2B78F CJK UNIFIED IDEOGRAPH-2B78F
        assertEquals("?", transform.action("𫞐")); // 2B790 CJK UNIFIED IDEOGRAPH-2B790
        assertEquals("?", transform.action("𫞑")); // 2B791 CJK UNIFIED IDEOGRAPH-2B791
        assertEquals("?", transform.action("𫞒")); // 2B792 CJK UNIFIED IDEOGRAPH-2B792
        assertEquals("?", transform.action("𫞓")); // 2B793 CJK UNIFIED IDEOGRAPH-2B793
        assertEquals("?", transform.action("𫞔")); // 2B794 CJK UNIFIED IDEOGRAPH-2B794
        assertEquals("?", transform.action("𫞕")); // 2B795 CJK UNIFIED IDEOGRAPH-2B795
        assertEquals("?", transform.action("𫞖")); // 2B796 CJK UNIFIED IDEOGRAPH-2B796
        assertEquals("?", transform.action("𫞗")); // 2B797 CJK UNIFIED IDEOGRAPH-2B797
        assertEquals("?", transform.action("𫞘")); // 2B798 CJK UNIFIED IDEOGRAPH-2B798
        assertEquals("?", transform.action("𫞙")); // 2B799 CJK UNIFIED IDEOGRAPH-2B799
        assertEquals("?", transform.action("𫞚")); // 2B79A CJK UNIFIED IDEOGRAPH-2B79A
        assertEquals("?", transform.action("𫞛")); // 2B79B CJK UNIFIED IDEOGRAPH-2B79B
        assertEquals("?", transform.action("𫞜")); // 2B79C CJK UNIFIED IDEOGRAPH-2B79C
        assertEquals("?", transform.action("𫞝")); // 2B79D CJK UNIFIED IDEOGRAPH-2B79D
        assertEquals("?", transform.action("𫞞")); // 2B79E CJK UNIFIED IDEOGRAPH-2B79E
        assertEquals("?", transform.action("𫞟")); // 2B79F CJK UNIFIED IDEOGRAPH-2B79F
        assertEquals("?", transform.action("𫞠")); // 2B7A0 CJK UNIFIED IDEOGRAPH-2B7A0
        assertEquals("?", transform.action("𫞡")); // 2B7A1 CJK UNIFIED IDEOGRAPH-2B7A1
        assertEquals("?", transform.action("𫞢")); // 2B7A2 CJK UNIFIED IDEOGRAPH-2B7A2
        assertEquals("?", transform.action("𫞣")); // 2B7A3 CJK UNIFIED IDEOGRAPH-2B7A3
        assertEquals("?", transform.action("𫞤")); // 2B7A4 CJK UNIFIED IDEOGRAPH-2B7A4
        assertEquals("?", transform.action("𫞥")); // 2B7A5 CJK UNIFIED IDEOGRAPH-2B7A5
        assertEquals("?", transform.action("𫞦")); // 2B7A6 CJK UNIFIED IDEOGRAPH-2B7A6
        assertEquals("?", transform.action("𫞧")); // 2B7A7 CJK UNIFIED IDEOGRAPH-2B7A7
        assertEquals("?", transform.action("𫞨")); // 2B7A8 CJK UNIFIED IDEOGRAPH-2B7A8
        assertEquals("?", transform.action("𫞩")); // 2B7A9 CJK UNIFIED IDEOGRAPH-2B7A9
        assertEquals("?", transform.action("𫞪")); // 2B7AA CJK UNIFIED IDEOGRAPH-2B7AA
        assertEquals("?", transform.action("𫞫")); // 2B7AB CJK UNIFIED IDEOGRAPH-2B7AB
        assertEquals("?", transform.action("𫞬")); // 2B7AC CJK UNIFIED IDEOGRAPH-2B7AC
        assertEquals("?", transform.action("𫞭")); // 2B7AD CJK UNIFIED IDEOGRAPH-2B7AD
        assertEquals("?", transform.action("𫞮")); // 2B7AE CJK UNIFIED IDEOGRAPH-2B7AE
        assertEquals("?", transform.action("𫞯")); // 2B7AF CJK UNIFIED IDEOGRAPH-2B7AF
        assertEquals("?", transform.action("𫞰")); // 2B7B0 CJK UNIFIED IDEOGRAPH-2B7B0
        assertEquals("?", transform.action("𫞱")); // 2B7B1 CJK UNIFIED IDEOGRAPH-2B7B1
        assertEquals("?", transform.action("𫞲")); // 2B7B2 CJK UNIFIED IDEOGRAPH-2B7B2
        assertEquals("?", transform.action("𫞳")); // 2B7B3 CJK UNIFIED IDEOGRAPH-2B7B3
        assertEquals("?", transform.action("𫞴")); // 2B7B4 CJK UNIFIED IDEOGRAPH-2B7B4
        assertEquals("?", transform.action("𫞵")); // 2B7B5 CJK UNIFIED IDEOGRAPH-2B7B5
        assertEquals("?", transform.action("𫞶")); // 2B7B6 CJK UNIFIED IDEOGRAPH-2B7B6
        assertEquals("?", transform.action("𫞷")); // 2B7B7 CJK UNIFIED IDEOGRAPH-2B7B7
        assertEquals("?", transform.action("𫞸")); // 2B7B8 CJK UNIFIED IDEOGRAPH-2B7B8
        assertEquals("?", transform.action("𫞹")); // 2B7B9 CJK UNIFIED IDEOGRAPH-2B7B9
        assertEquals("?", transform.action("𫞺")); // 2B7BA CJK UNIFIED IDEOGRAPH-2B7BA
        assertEquals("?", transform.action("𫞻")); // 2B7BB CJK UNIFIED IDEOGRAPH-2B7BB
        assertEquals("?", transform.action("𫞼")); // 2B7BC CJK UNIFIED IDEOGRAPH-2B7BC
        assertEquals("?", transform.action("𫞽")); // 2B7BD CJK UNIFIED IDEOGRAPH-2B7BD
        assertEquals("?", transform.action("𫞾")); // 2B7BE CJK UNIFIED IDEOGRAPH-2B7BE
        assertEquals("?", transform.action("𫞿")); // 2B7BF CJK UNIFIED IDEOGRAPH-2B7BF
        assertEquals("?", transform.action("𫟀")); // 2B7C0 CJK UNIFIED IDEOGRAPH-2B7C0
        assertEquals("?", transform.action("𫟁")); // 2B7C1 CJK UNIFIED IDEOGRAPH-2B7C1
        assertEquals("?", transform.action("𫟂")); // 2B7C2 CJK UNIFIED IDEOGRAPH-2B7C2
        assertEquals("?", transform.action("𫟃")); // 2B7C3 CJK UNIFIED IDEOGRAPH-2B7C3
        assertEquals("?", transform.action("𫟄")); // 2B7C4 CJK UNIFIED IDEOGRAPH-2B7C4
        assertEquals("?", transform.action("𫟅")); // 2B7C5 CJK UNIFIED IDEOGRAPH-2B7C5
        assertEquals("?", transform.action("𫟆")); // 2B7C6 CJK UNIFIED IDEOGRAPH-2B7C6
        assertEquals("?", transform.action("𫟇")); // 2B7C7 CJK UNIFIED IDEOGRAPH-2B7C7
        assertEquals("?", transform.action("𫟈")); // 2B7C8 CJK UNIFIED IDEOGRAPH-2B7C8
        assertEquals("?", transform.action("𫟉")); // 2B7C9 CJK UNIFIED IDEOGRAPH-2B7C9
        assertEquals("?", transform.action("𫟊")); // 2B7CA CJK UNIFIED IDEOGRAPH-2B7CA
        assertEquals("?", transform.action("𫟋")); // 2B7CB CJK UNIFIED IDEOGRAPH-2B7CB
        assertEquals("?", transform.action("𫟌")); // 2B7CC CJK UNIFIED IDEOGRAPH-2B7CC
        assertEquals("?", transform.action("𫟍")); // 2B7CD CJK UNIFIED IDEOGRAPH-2B7CD
        assertEquals("?", transform.action("𫟎")); // 2B7CE CJK UNIFIED IDEOGRAPH-2B7CE
        assertEquals("?", transform.action("𫟏")); // 2B7CF CJK UNIFIED IDEOGRAPH-2B7CF
        assertEquals("?", transform.action("𫟐")); // 2B7D0 CJK UNIFIED IDEOGRAPH-2B7D0
        assertEquals("?", transform.action("𫟑")); // 2B7D1 CJK UNIFIED IDEOGRAPH-2B7D1
        assertEquals("?", transform.action("𫟒")); // 2B7D2 CJK UNIFIED IDEOGRAPH-2B7D2
        assertEquals("?", transform.action("𫟓")); // 2B7D3 CJK UNIFIED IDEOGRAPH-2B7D3
        assertEquals("?", transform.action("𫟔")); // 2B7D4 CJK UNIFIED IDEOGRAPH-2B7D4
        assertEquals("?", transform.action("𫟕")); // 2B7D5 CJK UNIFIED IDEOGRAPH-2B7D5
        assertEquals("?", transform.action("𫟖")); // 2B7D6 CJK UNIFIED IDEOGRAPH-2B7D6
        assertEquals("?", transform.action("𫟗")); // 2B7D7 CJK UNIFIED IDEOGRAPH-2B7D7
        assertEquals("?", transform.action("𫟘")); // 2B7D8 CJK UNIFIED IDEOGRAPH-2B7D8
        assertEquals("?", transform.action("𫟙")); // 2B7D9 CJK UNIFIED IDEOGRAPH-2B7D9
        assertEquals("?", transform.action("𫟚")); // 2B7DA CJK UNIFIED IDEOGRAPH-2B7DA
        assertEquals("?", transform.action("𫟛")); // 2B7DB CJK UNIFIED IDEOGRAPH-2B7DB
        assertEquals("?", transform.action("𫟜")); // 2B7DC CJK UNIFIED IDEOGRAPH-2B7DC
        assertEquals("?", transform.action("𫟝")); // 2B7DD CJK UNIFIED IDEOGRAPH-2B7DD
        assertEquals("?", transform.action("𫟞")); // 2B7DE CJK UNIFIED IDEOGRAPH-2B7DE
        assertEquals("?", transform.action("𫟟")); // 2B7DF CJK UNIFIED IDEOGRAPH-2B7DF
        assertEquals("?", transform.action("𫟠")); // 2B7E0 CJK UNIFIED IDEOGRAPH-2B7E0
        assertEquals("?", transform.action("𫟡")); // 2B7E1 CJK UNIFIED IDEOGRAPH-2B7E1
        assertEquals("?", transform.action("𫟢")); // 2B7E2 CJK UNIFIED IDEOGRAPH-2B7E2
        assertEquals("?", transform.action("𫟣")); // 2B7E3 CJK UNIFIED IDEOGRAPH-2B7E3
        assertEquals("?", transform.action("𫟤")); // 2B7E4 CJK UNIFIED IDEOGRAPH-2B7E4
        assertEquals("?", transform.action("𫟥")); // 2B7E5 CJK UNIFIED IDEOGRAPH-2B7E5
        assertEquals("?", transform.action("𫟦")); // 2B7E6 CJK UNIFIED IDEOGRAPH-2B7E6
        assertEquals("?", transform.action("𫟧")); // 2B7E7 CJK UNIFIED IDEOGRAPH-2B7E7
        assertEquals("?", transform.action("𫟨")); // 2B7E8 CJK UNIFIED IDEOGRAPH-2B7E8
        assertEquals("?", transform.action("𫟩")); // 2B7E9 CJK UNIFIED IDEOGRAPH-2B7E9
        assertEquals("?", transform.action("𫟪")); // 2B7EA CJK UNIFIED IDEOGRAPH-2B7EA
        assertEquals("?", transform.action("𫟫")); // 2B7EB CJK UNIFIED IDEOGRAPH-2B7EB
        assertEquals("?", transform.action("𫟬")); // 2B7EC CJK UNIFIED IDEOGRAPH-2B7EC
        assertEquals("?", transform.action("𫟭")); // 2B7ED CJK UNIFIED IDEOGRAPH-2B7ED
        assertEquals("?", transform.action("𫟮")); // 2B7EE CJK UNIFIED IDEOGRAPH-2B7EE
        assertEquals("?", transform.action("𫟯")); // 2B7EF CJK UNIFIED IDEOGRAPH-2B7EF
        assertEquals("?", transform.action("𫟰")); // 2B7F0 CJK UNIFIED IDEOGRAPH-2B7F0
        assertEquals("?", transform.action("𫟱")); // 2B7F1 CJK UNIFIED IDEOGRAPH-2B7F1
        assertEquals("?", transform.action("𫟲")); // 2B7F2 CJK UNIFIED IDEOGRAPH-2B7F2
        assertEquals("?", transform.action("𫟳")); // 2B7F3 CJK UNIFIED IDEOGRAPH-2B7F3
        assertEquals("?", transform.action("𫟴")); // 2B7F4 CJK UNIFIED IDEOGRAPH-2B7F4
        assertEquals("?", transform.action("𫟵")); // 2B7F5 CJK UNIFIED IDEOGRAPH-2B7F5
        assertEquals("?", transform.action("𫟶")); // 2B7F6 CJK UNIFIED IDEOGRAPH-2B7F6
        assertEquals("?", transform.action("𫟷")); // 2B7F7 CJK UNIFIED IDEOGRAPH-2B7F7
        assertEquals("?", transform.action("𫟸")); // 2B7F8 CJK UNIFIED IDEOGRAPH-2B7F8
        assertEquals("?", transform.action("𫟹")); // 2B7F9 CJK UNIFIED IDEOGRAPH-2B7F9
        assertEquals("?", transform.action("𫟺")); // 2B7FA CJK UNIFIED IDEOGRAPH-2B7FA
        assertEquals("?", transform.action("𫟻")); // 2B7FB CJK UNIFIED IDEOGRAPH-2B7FB
        assertEquals("?", transform.action("𫟼")); // 2B7FC CJK UNIFIED IDEOGRAPH-2B7FC
        assertEquals("?", transform.action("𫟽")); // 2B7FD CJK UNIFIED IDEOGRAPH-2B7FD
        assertEquals("?", transform.action("𫟾")); // 2B7FE CJK UNIFIED IDEOGRAPH-2B7FE
        assertEquals("?", transform.action("𫟿")); // 2B7FF CJK UNIFIED IDEOGRAPH-2B7FF
        assertEquals("?", transform.action("𫠀")); // 2B800 CJK UNIFIED IDEOGRAPH-2B800
        assertEquals("?", transform.action("𫠁")); // 2B801 CJK UNIFIED IDEOGRAPH-2B801
        assertEquals("?", transform.action("𫠂")); // 2B802 CJK UNIFIED IDEOGRAPH-2B802
        assertEquals("?", transform.action("𫠃")); // 2B803 CJK UNIFIED IDEOGRAPH-2B803
        assertEquals("?", transform.action("𫠄")); // 2B804 CJK UNIFIED IDEOGRAPH-2B804
        assertEquals("?", transform.action("𫠅")); // 2B805 CJK UNIFIED IDEOGRAPH-2B805
        assertEquals("?", transform.action("𫠆")); // 2B806 CJK UNIFIED IDEOGRAPH-2B806
        assertEquals("?", transform.action("𫠇")); // 2B807 CJK UNIFIED IDEOGRAPH-2B807
        assertEquals("?", transform.action("𫠈")); // 2B808 CJK UNIFIED IDEOGRAPH-2B808
        assertEquals("?", transform.action("𫠉")); // 2B809 CJK UNIFIED IDEOGRAPH-2B809
        assertEquals("?", transform.action("𫠊")); // 2B80A CJK UNIFIED IDEOGRAPH-2B80A
        assertEquals("?", transform.action("𫠋")); // 2B80B CJK UNIFIED IDEOGRAPH-2B80B
        assertEquals("?", transform.action("𫠌")); // 2B80C CJK UNIFIED IDEOGRAPH-2B80C
        assertEquals("?", transform.action("𫠍")); // 2B80D CJK UNIFIED IDEOGRAPH-2B80D
        assertEquals("?", transform.action("𫠎")); // 2B80E CJK UNIFIED IDEOGRAPH-2B80E
        assertEquals("?", transform.action("𫠏")); // 2B80F CJK UNIFIED IDEOGRAPH-2B80F
        assertEquals("?", transform.action("𫠐")); // 2B810 CJK UNIFIED IDEOGRAPH-2B810
        assertEquals("?", transform.action("𫠑")); // 2B811 CJK UNIFIED IDEOGRAPH-2B811
        assertEquals("?", transform.action("𫠒")); // 2B812 CJK UNIFIED IDEOGRAPH-2B812
        assertEquals("?", transform.action("𫠓")); // 2B813 CJK UNIFIED IDEOGRAPH-2B813
        assertEquals("?", transform.action("𫠔")); // 2B814 CJK UNIFIED IDEOGRAPH-2B814
        assertEquals("?", transform.action("𫠕")); // 2B815 CJK UNIFIED IDEOGRAPH-2B815
        assertEquals("?", transform.action("𫠖")); // 2B816 CJK UNIFIED IDEOGRAPH-2B816
        assertEquals("?", transform.action("𫠗")); // 2B817 CJK UNIFIED IDEOGRAPH-2B817
        assertEquals("?", transform.action("𫠘")); // 2B818 CJK UNIFIED IDEOGRAPH-2B818
        assertEquals("?", transform.action("𫠙")); // 2B819 CJK UNIFIED IDEOGRAPH-2B819
        assertEquals("?", transform.action("𫠚")); // 2B81A CJK UNIFIED IDEOGRAPH-2B81A
        assertEquals("?", transform.action("𫠛")); // 2B81B CJK UNIFIED IDEOGRAPH-2B81B
        assertEquals("?", transform.action("𫠜")); // 2B81C CJK UNIFIED IDEOGRAPH-2B81C
        assertEquals("?", transform.action("𫠝")); // 2B81D CJK UNIFIED IDEOGRAPH-2B81D
    }
}
