name: Continuous Integration
on: [push, pull_request]
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Package
        run: mvn clean package
      - name: Get Final Artifact Name
        id: get-final-name
        run: |
          FINAL_NAME=$(mvn help:evaluate -Dexpression=project.build.finalName -q -DforceStdout)

          echo "final_name=$FINAL_NAME" >> $GITHUB_OUTPUT
      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: osmosis-kakasi-artifacts
          retention-days: 1
          path: |
            target/${{ steps.get-final-name.outputs.final_name }}.jar
            target/${{ steps.get-final-name.outputs.final_name }}-plugin.zip
