name: Deploy Package
on:
  push:
    tags:
      - '*.*.*'
permissions:
  contents: write
jobs:
  package-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Package
        run: mvn clean package
      - name: Generate TL Config Character Map Report
        run: mvn exec:java@generate-tl-config-character-map-report
      - name: Get Final Artifact Names
        id: get-final-name
        run: |
          FINAL_NAME=$(mvn help:evaluate -Dexpression=project.build.finalName -q -DforceStdout)

          echo "final_name=$FINAL_NAME" >> $GITHUB_OUTPUT
      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: osmosis-kakasi-artifacts
          path: |
            target/${{ steps.get-final-name.outputs.final_name }}.jar
            target/${{ steps.get-final-name.outputs.final_name }}-plugin.zip
            target/reports/tl-config-character-map-report.xlsx

  create-release:
    runs-on: ubuntu-latest
    needs: package-artifacts
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          name: osmosis-kakasi-artifacts
          path: artifacts
      - name: Create GitHub Release and upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            artifacts/*.jar
            artifacts/*.zip
            artifacts/tl-config-character-map-report.xlsx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
